POST http://192.168.0.108:110/upload?series=FionaPhoneTestDevice0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="111.txt"

< ./relative/path/to/local_file.txt
--WebAppBoundary--

###

